<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["posts/index", "Buscar posts"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["posts/new", "Crear "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Posts Existentes</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Content</th>
                <th>Created</th>
                <th>Editar</th>
                <th>Eliminar</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $post): ?>
            <tr>
                <td><?php echo $post->id ?></td>
                <td><?php echo $post->title ?></td>
                <td><?php echo $post->content ?></td>
                <td><?php echo $post->created_at ?></td>

                <td><?php echo $this->tag->linkTo(["posts/edit/" . $post->id, "Editar"]); ?></td>
                <td><?php echo $this->tag->linkTo(["posts/delete/" . $post->id, "Eliminar"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("posts/search", "Primera") ?></li>
                <li><?php echo $this->tag->linkTo("posts/search?page=" . $page->before, "<< Anterior") ?></li>
                <li><?php echo $this->tag->linkTo("posts/search?page=" . $page->next, "Siguiente >>") ?></li>
                <li><?php echo $this->tag->linkTo("posts/search?page=" . $page->last, "Ultima") ?></li>
            </ul>
        </nav>
    </div>
</div>
